CREATE TABLE `VX_aln_ra_feed` (
  `rafeed_id` bigint(16) unsigned NOT NULL AUTO_INCREMENT,
  `ticket_number` bigint(15) NOT NULL,
  `coupon_number`  varchar(60)NOT NULL,
  `booking_country` int(11) NOT NULL,
  `booking_city` int(11)NOT NULL,
  `issuance_country` int(11) NOT NULL,
  `issuance_city`  int(11) NOT NULL,
    `boarding_point` int(11) NOT NULL,
  `off_point` int(11) NOT NULL,
`prorated_price` int(11) NOT NULL,
  `cabin` int(11) NOT NULL,
  `class` varchar(60) NOT NULL,
`booking_date`  int(11) NOT NULL,
 `departure_date`  int(11) NOT NULL,
`day_of_week` int(11) NOT NULL,
  `days_to_departure` int(11) NOT NULL,
  `operating_airline_code` int(11) NOT NULL,
   `marketing_airline_code` int(11) NOT NULL,
  `flight_number` varchar(60) NOT NULL,
  `office_id` varchar(60) NOT NULL,
  `channel` varchar(60) NOT NULL,
  `pax_type` int(11) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `create_userID` int(11) NOT NULL,
  `modify_userID` int(11) NOT NULL,
  `create_date` int(11) NOT NULL,
  `modify_date` int(11) NOT NULL,
  PRIMARY KEY (`rafeed_id`),
  KEY `ticket_number_indx` (`ticket_number`),
   KEY `cpn_number_indx` (`coupon_number`),
  KEY `operating_airline_code_indx` (`operating_airline_code`),
  KEY `marketing_airline_code_indx` (`marketing_airline_code`),
   KEY `booking_country_indx` (`booking_country`),
  KEY `booking_city_indx` (`booking_city`),
  KEY `issuance_country_indx` (`issuance_country`),
  KEY `issuance_city_indx` (`issuance_city`),
  KEY `boarding_point_indx` (`boarding_point`),
  KEY `off_point_indx` (`off_point`),
    KEY `class_indx` (`class`),
  KEY `day_of_week_indx` (`day_of_week`),
  KEY `days_to_departure_indx` (`days_to_departure`),
KEY `booking_date_indx` (`booking_date`),
 KEY `departure_date_indx` (`departure_date`),
  KEY `flight_number_indx` (`flight_number`),
  KEY `prorated_price_indx` (`prorated_price`),
  KEY `cabin_indx` (`cabin`),
  KEY `office_id_indx` (`office_id`),
  KEY `channel_indx` (`channel`),
  KEY `pax_type_indx` (`pax_type`),
  KEY `active_indx` (`active`),
  KEY `createuser_indx` (`create_userID`),
  KEY `modifyuser_indx` (`modify_userID`),
  KEY `createdate_indx` (`create_date`),
  KEY `modifydate_indx` (`modify_date`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

update vx_aln_data_defns set code='Y' WHERE aln_data_typeID = 13 AND aln_data_value = 'Economy';
update vx_aln_data_defns set code='W' WHERE aln_data_typeID = 13 AND aln_data_value = 'Premium ECO';
update vx_aln_data_defns set code='C' WHERE aln_data_typeID = 13 AND aln_data_value = 'Business';
 update vx_aln_data_defns set code='F' WHERE aln_data_typeID = 13 AND aln_data_value = 'First';
