drop table activities;;
drop table activitiescategory;
drop table alert;
drop table attendance;
drop table automation_rec;
drop table automation_shudulu;
drop table category;
drop table certificate_template;
drop table complain;
drop table event;
drop table eventcounter;
drop table feetypes;
drop table holiday;
drop table invoice;
drop table location;
drop table mailandsms;
drop table mailandsmstemplate;
drop table mailandsmstemplatetag;
drop table make_payment;
drop table manage_salary;
drop table media;
drop table media_category;
drop table media_share;
drop table message;
drop table migrations;
drop table notice;
drop table payment;
drop table reply_msg;
drop table reset;
drop table salary_option;
drop table salary_template;
drop table systemadmin;
drop table transport;
drop table uattendance;
drop table vendor;

 update menu set status = 0 where menuID =11;
 update menu set status = 0 where menuID =12;
 update menu set status = 0 where menuID =100;
 update menu set status = 0 where menuID =41;
update menu set status = 0 where menuID =19;