CREATE TABLE `BG_baggage_control_rule` (
  `bclr_id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `carrierID` int(11) NOT NULL,
  `from_cabin` int(11) NOT NULL,
  `partner_carrierID` int(11) NOT NULL,
  `allowance` tinyint(1) NOT NULL,
  `aircraft_typeID` int(11) NOT NULL,
  `flight_num_range` varchar(150) NOT NULL,
  `origin_level` int(11) NOT NULL,
  `origin_content` varchar(250) NOT NULL,
  `dest_level` int(11) NOT NULL,
  `dest_content` varchar(250) NOT NULL,
  `effective_date` int(11) NOT NULL,
  `discontinue_date` int(11) NOT NULL,
  `season_id` int(11) NOT NULL DEFAULT 0,
  `frequency` int(11) NOT NULL,
  `bag_type` tinyint(11) NOT NULL,
  `rule_auth` int(11) NOT NULL,
  `dep_time_start` int(11) NOT NULL,
  `dep_time_end` int(11) NOT NULL,
  `min_unit` int(11) NOT NULL,
  `max_capacity` int(11) NOT NULL,
  `min_price` int(11) NOT NULL,
  `max_price` int(11) NOT NULL,
  `active` tinyint(1) NOT NULL DEFAULT '1',
  `create_userID` int(11) unsigned NOT NULL,
  `modify_userID` int(11) unsigned NOT NULL,
  `create_date` int(11) unsigned NOT NULL,
  `modify_date` int(11) unsigned NOT NULL,
   PRIMARY KEY (`bclr_id`),
  KEY `carrier_indx` (`carrierID`),
  KEY `partner_carrierID_indx` (`partner_carrierID`),
  KEY `allowance_indx` (`allowance`),
  KEY `aircraft_typeID_indx` (`aircraft_typeID`),
  KEY `flight_num_range_indx` (`flight_num_range`),
  KEY `origin_level_indx` (`origin_level`),
  KEY `dest_level_indx` (`dest_level`),
  KEY `effective_date_indx` (`effective_date`),
  KEY `discontinue_date_indx` (`discontinue_date`),
  KEY `season_id_indx` (`season_id`),
  KEY `frequency_indx` (`frequency`),
  KEY `bag_type_indx` (`bag_type`),
  KEY `rule_auth_indx` (`rule_auth`),
  KEY `dep_time_start_indx` (`dep_time_start`),
  KEY `dep_time_end_indx` (`dep_time_end`),
  KEY `min_unit_indx` (`min_unit`),
  KEY `max_capacity_indx` (`max_capacity`),
  KEY `min_price_indx` (`min_price`),
  KEY `max_price_indx` (`max_price`),
  KEY `active_indx` (`active`),
  KEY `createuser_indx` (`create_userID`),
  KEY `modifyuser_indx` (`modify_userID`),
  KEY `createdate_indx` (`create_date`),
  KEY `modifydate_indx` (`modify_date`)
);