CREATE TABLE `up_ra_feed_baggage` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `airline_code` int(11) NOT NULL,
 `emd_nbr` bigint(16) NOT NULL,
 `coupon_number` int(1) NOT NULL,
 `carrier` int(11) NOT NULL,
 `flight_number` int(4) NOT NULL,
 `boarding_point` int(11) NOT NULL,
 `off_point` int(11) NOT NULL,
 `prorated_price` decimal(10,2) NOT NULL,
 `class` char(1) NOT NULL,
 `departure_date` int(11) NOT NULL,
 `day_of_week` int(11) NOT NULL,
 `fare_basis` varchar(15) NOT NULL,
 `cabin` int(11) NOT NULL,
 `marketing_airline_code` int(11) NOT NULL,
 `operating_airline_code` int(11) NOT NULL,
 `season_id` int(11) DEFAULT NULL,
 `office_id` varchar(8) NOT NULL,
 `channel` varchar(20) NOT NULL,
 `pax_type` int(11) NOT NULL,
 `origin` int(11) NOT NULL,
 `destinition` int(11) NOT NULL,
 `rate_per_unit` varchar(15) NOT NULL,
 `weight` varchar(15) NOT NULL,
 `currency` varchar(15) NOT NULL,
 `rfic` varchar(1) NOT NULL,
 `rfisc` varchar(5) NOT NULL,
 `ssr_code` varchar(6) NOT NULL,
 `create_date` int(11) NOT NULL,
 `modify_date` int(11) NOT NULL,
 `create_userID` int(11) NOT NULL,
 `modify_userID` int(11) NOT NULL,
 `season_record` int(11) NOT NULL DEFAULT '0',
 `sub_season_record` int(11) NOT NULL DEFAULT '0',
 `active` tinyint(1) NOT NULL DEFAULT '1',
 PRIMARY KEY (`id`)
)